### ISSUE TITLE
PEP8 / Auto-Lint / Code-Style

### ISSUE THREAD

**Issue by romangraef** [werewolves-devs/Werewolf_Bot#107]
Currently our Codebase is rated a -0.22/10 in codestyle by Pylint. So i just wanted to put some hints and suggestions out there:

If you are using an IDE please look up if it has some kind of autoformat option. 

 - IntelliJ has `STRG+ALT+L` or `Code -> Reformat Code`
 - Atom has a plugin called `atom-beautify`
 - VS Code has `STRG+SHIFT+I` or `STRG+SHIT+P -> Beautify file`

Another thing we might want to look into is a [.editorconfig](https://editorconfig.org/). Since multiple IDEs handle autoformatting different, we need some way to standardize our (for example) indents.
I would like to hear your thoughts on that one before doing it. 

Last but not least we might want to have a `pylint` script in our `.travis.yml` to prevent merges which lower those standards too much.

**Comment by romangraef** [comment]
Vote on this comment with :+1: if you want an `.editorconfig` and with an :-1: if not

**Comment by Bentechy66** [comment]
All those suggestions sound great - though Randium might not like it :/

**Comment by romangraef** [comment]
All we want to do, is using the shortcuts that i listed...

**Comment by Randium** [comment]
Yes, but that's my question. _What does it do?_

**Comment by romangraef** [comment]
It changes the autoformat to be the same accross *most* IDEs

**Comment by Randium** [comment]
I'm closing this issue, as the branch has been successfully merged.
