### ISSUE TITLE
Co-existence of bots in one structure

### ISSUE THREAD

**Issue by Randium** [werewolves-devs/Werewolf_Bot#14]
Concerning the database and all the bots, I thought it wouldn't hurt if all bots were kinda squished together in one folder, the same folder where the database resides in.
Yes, we're building an API, and we won't need to do this, but the way the werewolf bot is being built, is a structure that most bots need.
Sure, a few bots have some technical sides that aren't included in the bot, like the cc bot and the poll bot, but most other bots share the same structure; gain info, process it, get and set the database, and send back a message.
Look at the Devil Bot. It's literally a small Werewolf Bot. The Devil chooses a target, the target is added to a channel, souls are exchanged or fakeroles are revealed from the database, and a message is sent back. Boom. That's it.

This is why I'm thinking we could use this repository for other bots as well. Like Vyryn said, let's not focus on other bots while the basics aren't here yet, but it is something to think about. The structure's here. If we organize everything neatly in the right folders, we could have a simple but strong structure in which we can easily add more bots.

Let me know what you think.

**Comment by Bentechy66** [comment]
Interesting idea. Perhaps users should `git clone` into a `plugins` directory or something. This will allow for organized repos, independent updates and better organization.

**Comment by Randium** [comment]
All bots share one config, the database could be easily reached, including those functions that make it so easy to reach it, logic puzzles would be just like the werewolf bot's....

...the only downside is that this won't work for bots written in different languages. But they'd need to be separated and written independently, whether we use this idea or not.

**Comment by Bentechy66** [comment]
Hmm. Perhaps there could be an `external_plugins/` folder, which contains bots written in other languages. They could be started seperately, or perhaps from a config, such as http://git.bentechy66.me/snippets/3

Another possibility is for them to be loaded dynamically, using functions such as `plugins.start_module("CC-Bot", "index.js", "node")`

However, we probably shouldn't even be thinking about this, as we are not nearly at this point yet.

**Comment by ed588** [comment]
I think if we *do* do this then we should use git submodules, which is a git feature that allows an entirely separate git repository to act like a folder inside another one. This would keep code for different bots separate, in different github repos (meaning different people can work on them more easily), while still keeping everything in one central place.

> However, we probably shouldn't even be thinking about this, as we are not nearly at this point yet.
Agreed. I haven't been that involved on the main bot but from what I've heard, you aren't there yet.

On a related note, the API structure is basically finished and code can be added to make endpoints, if we do decide to use that.
