### ISSUE TITLE
TODO: Send a DM when given a user's id

### ISSUE THREAD

**Issue by Randium** [werewolves-devs/Werewolf_Bot#38]
This part still needs to be filled in.

https://github.com/werewolves-devs/Werewolf_Bot/blob/59ec55b6a35cc236b5c6e0dbb3d3045833129e68/main.py#L113

Is this how we can do TODOs? Let me know if there's a better way, else we can just create todo stuff this way.

**Comment by Bentechy66** [comment]
Which channel are you trying to get?

**Comment by Randium** [comment]
Commit https://github.com/werewolves-devs/Werewolf_Bot/commit/3a0d38fcb49c1324b99995dbbc26edec3d6777f2 should have resolved this issue. I will test this now in the field.

**Comment by Randium** [comment]
This issue has been solved. The structure does not allow embeds to be sent in DMs, but as long as it isn't required, this issue will remain closed.

Consider it done.
