### ISSUE TITLE
A way to contribute

### ISSUE THREAD

**Issue by CommandLord** [werewolves-devs/Werewolf_Bot#4]
If you would like people to contribute, it would be nice if you could make some kind of introduction on how to. Having an overview of the state, plan and function would be really helpful. You could also organize some tasks within the projects tab.

Oh, and there is some thing I would like to try... @everyone ... it would be interesting to know if the GitHub bot could somehow tag everyone...

**Comment by ed588** [comment]
> Having an overview of the state, plan and function would be really helpful. 

We don't actually have a full plan yet lol :p

**Comment by HurricanKai** [comment]
(just testing sorry <@140424290171486208>)

**Comment by Randium** [comment]
I've just opened a folder called story_time in my pull request. Once that one's merged with the main bot, we can allow people to write some story_time in there.
Also, for the more technical and programming skilled users, if you find the text #TODO anywhere in the code, and you think you can write a function that does the trick, then go ahead!
If you don't know what exactly needs to be done, always feel free to ask. 🤗

**Comment by Bentechy66** [comment]
Re-opening issue because contribution guidelines are still not in repo

**Comment by Randium** [comment]
What guidelines are there to make? As long as it fits the plan, anyone can contribute.

**Comment by Bentechy66** [comment]
Implemented with my README update
