### ISSUE TITLE
TODO: Add Mailbox.poll(channel_id, purpose = "kill") command

### ISSUE THREAD

**Issue by Randium** [werewolves-devs/Werewolf_Bot#44]
This command should receive a command to create a poll in a given channel_id.

The purpose is set to default, but should basically always set up with a given reason.

wolf - poll for the wolves to kill a victim
lynch - poll for the townspeople to choose a victim to kill
mayor - poll for the townspeople to lynch a victim
reporter - poll for the townspeople to elect a reporter
cult - poll for the cult to kill a victim
swamp - poll for the abducted to kill The Thing

The Mailbox shouldn't care too much about the purposes, any string should be accepted, but these are (for now) the purposes that we should use in the database to evaluate.

**Comment by Bentechy66** [comment]
Do abductees vote to kill someone in the swamp

**Comment by Randium** [comment]
At first, I had in mind that the town could be considered as a separate town; flute players could still enchant, but only other people in the swamp. Wolves could kill abducted people, etc. However, this idea is (obviously) too cool and not worth the effort (despite being hella cool).
Instead, they just become like people in a horror movie - stupid, powerless people. HOWEVER, if they unanimously vote on one of them, and that player is The Thing, then The Thing dies and all the avbucted are freed. Obviously, The Thing's vote doesn't count and all members must have voted.

**Comment by Randium** [comment]
However, keep in mind that The Thing knows the roles of all abducted players, AND can kill one of them each night.

**Comment by Randium** [comment]
I am unsure yet if the player dies if that player wasn't The Thing. I think they should.

**Comment by Bentechy66** [comment]
I think they should die

**Comment by Randium** [comment]
So do I. Else it'll become pretty obvious at some point. 5 abducted would take to 5 nights to sweep, and if they didn't die, people would slowly be proven.

**Comment by Randium** [comment]
It still needs to be unanimous, however.

**Comment by Randium** [comment]
Alright, here's a quick update.

The structure's here. The bot can create polls and evaluate them, as long as participants vote on the structure. It has a list of instructions in main.py that can be filled in to have the bot do whatever is wished for given results.

There's two more things that need to be done;
SECRET VOTES - some votes, like raven's threatens, do not seem to work as intended, and the bot seems to ignore them completely.. This will need to be fixed soon.
ADD CHANNEL COLUMN TO DATABASE - apparently, get_message() is now a function that can only be applied to channels specific, meaning that one needs to know the channel to gain the message's content. This is fine, but it means we will need to store the channel in which the poll is held.

Once these two are done, polls are fully functional and can easily be used by interpretation\ww_head.py to create and evaluate polls.

**Comment by Randium** [comment]
Oi oi! Greetings from the other side, Discord! Italy's lovely, and I wanted to give a message to all the bot developers; thank you for reviewing and merging the polls branch already!

For those who do not know yet; both issues referenced in the last message here have been fixed. The polls are ready and I just need one person to accept and merge the request. Also, if you need help, just open an issue so I can assist you!

Oh, and tell romangraef89o the three weeks have passed. Let them inspect the bot, please. (AND LET THEM ACCEPT OR AT LEAST REVIEW THE POLLS BRANCH IF YOU CAN'T DO IT YOURSELVES FOR GODS SAKE)

**Comment by Bentechy66** [comment]
Sorry, just realized that was waaaaaaaay too formal. I've just been emailing some teachers and organizations and I'm still in formal mode. :/

**Comment by Randium** [comment]
Whoops, hadn't noticed them yet, sorry!
I'll look into them. Thanks.

**Comment by Randium** [comment]
I'm closing this issue now as the poll commands are now fully functional.
