### ISSUE TITLE
Conspiracy Channel Guidelines

### ISSUE THREAD

**Issue by Randium** [werewolves-devs/Werewolf_Bot#83]
If you have the following number in the database, you have that and *only that* role;
**0** - ( ~~read~~ ~~write~~ ) - **participant** *(no access)*
**1** - ( READ WRITE ) - **participant** *(access)*
**2** - ( READ ~~write~~ ) - **frozen** *(frozen)*
**3** - ( ~~read~~ ~~write~~ ) - **participant** *(abducted)*
**4** - ( READ ~~write~~ ) - **dead participant** *(dead)*
**5** - ( READ ~~write~~ ) - **participant** *(mute)*
**6** - ( ~~read~~ ~~write~~ ) - **participant** *(abducted mute)*
**7** - ( ~~read~~ ~~write~~ ) -  **dead participant** *(abducted dead)*
**8** - ( ~~read~~ ~~write~~ ) - **suspended** *(suspended)*

One could take care of this by simply removing all roles from a player and adding only that role to the user.

**Comment by Randium** [comment]
With pull request #85, this has been taken care of and will now be closed until changes are made or new numbers are added.

**Comment by ed588** [comment]
if you keep looking at it you should consider using an [enum](https://docs.python.org/3/library/enum.html) or similar to give it a nicer name in the code. Or not, idk.

**Comment by Randium** [comment]
We're gonna make an enum for this in the new version. This issue will soon be closed. Yay!
